Add network-explorer
streamr-dev/streamr-docker-dev pull request #85
Opened 2020-11-12 06:07 UTC by tumppi

Adds network-explorer running on port 3334.

2020-11-16 16:07 UTC, hpihkala requested changes
We should probably expose this from nginx so that we can access it over https in staging. 

You could take a look at the config for the `sidechain-http` upstream, and just copy [this bit](https://github.com/streamr-dev/streamr-docker-dev/blob/master/custom-nginx-reverse-proxy.conf#L37-L39) and [this bit](https://github.com/streamr-dev/streamr-docker-dev/blob/master/custom-nginx-reverse-proxy.conf#L132-L134) as a starting point and modify them. Please let me know if you need help with that!

Additionally one question and one comment below.

2020-11-17 06:36 UTC, tumppi commented on docker-compose.override.yml
> +        stdin_open: true
It's a feature of create-react-app: https://github.com/facebook/create-react-app/issues/8688#issuecomment-642309787. If we leave that out the container just exits when it's ready to serve requests.

2020-11-17 08:25 UTC, tumppi commented
Nginx configuration is now added 👍

2020-11-17 18:26 UTC, hpihkala approved these changes

2020-11-18 06:35 UTC, merged